"""Donnees du monde, GENEREES. Ne pas editer a la main.

Regenerer avec tools/build_apworld_data.py, qui lit
data/locations_bis.csv et data/pieces_attaque.csv, eux-memes
regeneres depuis la ROM.
"""

BASE_ID = 0xb15000
RESERVE_HORS_TABLE = 1024

# (identifiant TreasureInfo, nom de location, item d'origine, zone)
TREASURES = [
    (0, 'Pump Works - Block 0', 'Mushroom', 'Pump Works'),
    (1, 'Pump Works - Block 1', 'Retry Clock', 'Pump Works'),
    (2, 'Pump Works - Block 2', '10 Coins', 'Pump Works'),
    (3, 'Pump Works - Block 3', '1-Up Mushroom', 'Pump Works'),
    (4, 'Pump Works - Block 4', '5 Coins', 'Pump Works'),
    (5, 'Pump Works - Block 5', 'Super Mushroom', 'Pump Works'),
    (7, 'Pump Works - Block 7', 'Fighter Wear', 'Pump Works'),
    (9, 'Pump Works - Block 9', '5 Coins', 'Pump Works'),
    (10, 'Pump Works - Block 10', 'Syrup Jar', 'Pump Works'),
    (12, 'Pump Works - Block 12', 'Mushroom', 'Pump Works'),
    (13, 'Pump Works - Block 13', '10 Coins', 'Pump Works'),
    (14, 'Pump Works - Block 14', 'Nut', 'Pump Works'),
    (15, 'Pump Works - Block 15', 'Picnic Wear', 'Pump Works'),
    (16, 'Plack Beach - Block 16', '50 Coins', 'Plack Beach'),
    (17, 'Plack Beach - Block 17', 'Ultrasyrup Jar', 'Plack Beach'),
    (18, 'Plack Beach - Block 18', '100 Coins', 'Plack Beach'),
    (19, 'Plack Beach - Block 19', '50 Coins', 'Plack Beach'),
    (20, 'Plack Beach - Block 20', 'Max Nut', 'Plack Beach'),
    (21, 'Plack Beach - Block 21', '50 Coins', 'Plack Beach'),
    (22, 'Plack Beach - Block 22', '50 Coins', 'Plack Beach'),
    (23, 'Plack Beach - Block 23', 'Refreshing Herb', 'Plack Beach'),
    (24, 'Plack Beach - Block 24', '100 Coins', 'Plack Beach'),
    (25, 'Plack Beach - Block 25', 'Supersyrup Jar', 'Plack Beach'),
    (26, 'Plack Beach - Block 26', 'Heart Wear', 'Plack Beach'),
    (27, 'Plack Beach - Block 27', '50 Coins', 'Plack Beach'),
    (28, 'Plack Beach - Block 28', 'Star Candy', 'Plack Beach'),
    (29, 'Plack Beach - Block 29', '50 Coins', 'Plack Beach'),
    (30, 'Plack Beach - Block 30', '5 Coins', 'Plack Beach'),
    (31, 'Plack Beach - Bean 31', 'Heart Bean', 'Plack Beach'),
    (32, 'Plack Beach - Block 32', 'Super Nut', 'Plack Beach'),
    (33, "Peach's Castle - Block 33", '50 Coins', "Peach's Castle"),
    (34, 'Plack Beach - Block 34', 'Big Stomp Boots', 'Plack Beach'),
    (35, 'Plack Beach - Block 35', '50 Coins', 'Plack Beach'),
    (36, 'Plack Beach - Block 36', '5 Coins', 'Plack Beach'),
    (37, 'Plack Beach - Block 37', 'Ultra Mushroom', 'Plack Beach'),
    (38, 'Plack Beach - Block 38', '5 Coins', 'Plack Beach'),
    (39, 'Dimble Wood - Brick 39', '50 Coins', 'Dimble Wood'),
    (40, 'Dimble Wood - Block 40', 'Retry Clock', 'Dimble Wood'),
    (41, 'Dimble Wood - Brick 41', 'Retry Clock', 'Dimble Wood'),
    (43, 'Dimble Wood - Block 43', '50 Coins', 'Dimble Wood'),
    (44, 'Dimble Wood - Block 44', 'Max Nut', 'Dimble Wood'),
    (45, 'Dimble Wood - Block 45', '100 Coins', 'Dimble Wood'),
    (46, 'Dimble Wood - Block 46', '100 Coins', 'Dimble Wood'),
    (47, 'Flab Zone - Block 47', 'Retry Clock', 'Flab Zone'),
    (48, 'Flab Zone - Block 48', '5 Coins', 'Flab Zone'),
    (49, 'Flab Zone - Block 49', 'Super Mushroom', 'Flab Zone'),
    (50, 'Flab Zone - Block 50', 'Super Mushroom', 'Flab Zone'),
    (51, 'Flab Zone - Block 51', '5 Coins', 'Flab Zone'),
    (52, 'Flab Zone - Block 52', 'Supersyrup Jar', 'Flab Zone'),
    (53, 'Flab Zone - Block 53', 'Super Nut', 'Flab Zone'),
    (54, 'Flab Zone - Block 54', 'POW Boots', 'Flab Zone'),
    (55, 'Flab Zone - Block 55', '10 Coins', 'Flab Zone'),
    (56, 'Flab Zone - Block 56', '50 Coins', 'Flab Zone'),
    (57, 'Flab Zone - Block 57', 'Syrup Jar', 'Flab Zone'),
    (58, 'Flab Zone - Block 58', '1-Up Mushroom', 'Flab Zone'),
    (59, 'Flab Zone - Block 59', '5 Coins', 'Flab Zone'),
    (60, 'Flab Zone - Block 60', '10 Coins', 'Flab Zone'),
    (61, 'Flab Zone - Block 61', 'Supersyrup Jar', 'Flab Zone'),
    (62, 'Flab Zone - Block 62', '25 Coins', 'Flab Zone'),
    (63, 'Flab Zone - Block 63', 'Super Mushroom', 'Flab Zone'),
    (64, 'Flab Zone - Block 64', '100 Coins', 'Flab Zone'),
    (66, 'Bowser Path - Block 66', 'POW Mush Jam', 'Bowser Path'),
    (67, 'Dimble Wood - Block 67', '100 Coins', 'Dimble Wood'),
    (70, 'Dimble Wood - Grass 70', '1 Coins', 'Dimble Wood'),
    (71, 'Dimble Wood - Brick 71', '10 Coins', 'Dimble Wood'),
    (73, 'Dimble Wood - Grass 73', '10 Coins', 'Dimble Wood'),
    (74, 'Dimble Wood - Grass 74', '10 Coins', 'Dimble Wood'),
    (75, 'Dimble Wood - Grass 75', '10 Coins', 'Dimble Wood'),
    (76, 'Dimble Wood - Brick 76', 'Hot Drumstick', 'Dimble Wood'),
    (77, 'Dimble Wood - Brick 77', '50 Coins', 'Dimble Wood'),
    (78, 'Dimble Wood - Brick 78', 'Retry Clock', 'Dimble Wood'),
    (79, 'Dimble Wood - Brick 79', 'Hard Ring', 'Dimble Wood'),
    (80, 'Dimble Wood - Brick 80', 'Syrup Jar', 'Dimble Wood'),
    (81, 'Bowser Path - Brick 81', '10 Coins', 'Bowser Path'),
    (82, 'Dimble Wood - Bean 82', 'Heart Bean', 'Dimble Wood'),
    (83, 'Dimble Wood - Bean 83', 'Heart Bean', 'Dimble Wood'),
    (84, 'Bumpsy Plains - Bean 84', 'Heart Bean', 'Bumpsy Plains'),
    (86, 'Bumpsy Plains - Block 86', '100 Coins', 'Bumpsy Plains'),
    (87, 'Bumpsy Plains - Block 87', '250 Coins', 'Bumpsy Plains'),
    (88, 'Bowser Castle - Block 88', '100 Coins', 'Bowser Castle'),
    (89, 'Bowser Castle - Block 89', '50 Coins', 'Bowser Castle'),
    (90, 'Blubble Lake - Brick 90', 'Retry Clock', 'Blubble Lake'),
    (91, 'Bumpsy Plains - Brick 91', '50 Coins', 'Bumpsy Plains'),
    (92, 'Bumpsy Plains - Brick 92', 'Safety Ring', 'Bumpsy Plains'),
    (93, 'Bumpsy Plains - Brick 93', 'Minion Band', 'Bumpsy Plains'),
    (94, 'Bumpsy Plains - Brick 94', 'Star Candy', 'Bumpsy Plains'),
    (95, 'Bowser Path - Brick 95', 'Power Band', 'Bowser Path'),
    (96, 'Bowser Path - Block 96', 'Bye-Bye Gloves', 'Bowser Path'),
    (97, 'Bowser Castle - Brick 97', 'Supersyrup Jar', 'Bowser Castle'),
    (98, 'Bowser Castle - Brick 98', 'Supersyrup Jar', 'Bowser Castle'),
    (99, 'Blubble Lake - Bean 99', 'Special Bean', 'Blubble Lake'),
    (100, 'Blubble Lake - Bean 100', 'Heart Bean', 'Blubble Lake'),
    (101, 'Blubble Lake - Bean 101', 'Power Bean', 'Blubble Lake'),
    (102, 'Blubble Lake - Bean 102', 'Special Bean', 'Blubble Lake'),
    (103, 'Blubble Lake - Bean 103', 'Heart Bean', 'Blubble Lake'),
    (104, 'Blubble Lake - Bean 104', 'Heart Bean', 'Blubble Lake'),
    (105, 'Blubble Lake - Bean 105', 'Power Bean', 'Blubble Lake'),
    (106, 'Blubble Lake - Bean 106', 'Heart Bean', 'Blubble Lake'),
    (107, 'Toad Town - Block 107', 'Super Nut', 'Toad Town'),
    (108, 'Toad Town - Block 108', '50 Coins', 'Toad Town'),
    (109, 'Toad Town - Block 109', '100 Coins', 'Toad Town'),
    (110, 'Toad Town - Block 110', '50 Coins', 'Toad Town'),
    (111, 'Toad Town - Block 111', 'Star Candy', 'Toad Town'),
    (112, 'Toad Town - Block 112', '50 Coins', 'Toad Town'),
    (113, 'Toad Town - Block 113', '50 Coins', 'Toad Town'),
    (114, 'Toad Town - Block 114', 'Super Mushroom', 'Toad Town'),
    (115, 'Toad Town - Block 115', 'Supersyrup Jar', 'Toad Town'),
    (116, 'Toad Town - Block 116', 'Supersyrup Jar', 'Toad Town'),
    (117, 'Toad Town - Block 117', '100 Coins', 'Toad Town'),
    (118, 'Toad Town - Block 118', 'Coin Socks', 'Toad Town'),
    (119, 'Toad Town - Block 119', '50 Coins', 'Toad Town'),
    (120, 'Toad Town - Block 120', '50 Coins', 'Toad Town'),
    (121, 'Toad Town - Block 121', '10 Coins', 'Toad Town'),
    (122, 'Toad Town - Block 122', '50 Coins', 'Toad Town'),
    (123, 'Toad Town - Block 123', '100 Coins', 'Toad Town'),
    (124, 'Toad Town - Block 124', 'Mushroom Stone', 'Toad Town'),
    (125, 'Bowser Castle - Brick 125', 'Fiery Drumstick', 'Bowser Castle'),
    (126, 'Tower of Yikk - Brick 126', 'Drumstick Ring', 'Tower of Yikk'),
    (127, 'Toad Town - Block 127', '10 Coins', 'Toad Town'),
    (128, 'Toad Town - Block 128', '50 Coins', 'Toad Town'),
    (129, 'Toad Town - Block 129', '500 Coins', 'Toad Town'),
    (130, 'Toad Town - Block 130', 'Ultra Mushroom', 'Toad Town'),
    (131, 'Toad Town - Block 131', 'Muscle Wear', 'Toad Town'),
    (132, 'Toad Town - Block 132', 'Retry Clock', 'Toad Town'),
    (133, 'Toad Town - Block 133', 'Max Nut', 'Toad Town'),
    (134, 'Toad Town - Block 134', '100 Coins', 'Toad Town'),
    (135, 'Plack Beach - Brick 135', '50 Coins', 'Plack Beach'),
    (136, 'Tunnel - Brick 136', 'Rock Shell', 'Tunnel'),
    (137, 'Tunnel - Brick 137', '100 Coins', 'Tunnel'),
    (138, 'Energy Hold - Block 138', 'Super Nut', 'Energy Hold'),
    (139, 'Energy Hold - Block 139', '50 Coins', 'Energy Hold'),
    (140, 'Energy Hold - Block 140', 'Super Mushroom', 'Energy Hold'),
    (141, 'Energy Hold - Block 141', '50 Coins', 'Energy Hold'),
    (142, 'Energy Hold - Block 142', '100 Coins', 'Energy Hold'),
    (143, 'Energy Hold - Block 143', 'Star Candy', 'Energy Hold'),
    (144, 'Energy Hold - Block 144', 'Special Boots', 'Energy Hold'),
    (146, 'Energy Hold - Block 146', 'Super Mushroom', 'Energy Hold'),
    (147, 'Energy Hold - Block 147', 'Nurse Socks', 'Energy Hold'),
    (148, 'Energy Hold - Block 148', '100 Coins', 'Energy Hold'),
    (149, 'Energy Hold - Block 149', 'Supersyrup Jar', 'Energy Hold'),
    (150, 'Dimble Wood - Block 150', '1-Up Deluxe', 'Dimble Wood'),
    (151, 'Energy Hold - Block 151', '50 Coins', 'Energy Hold'),
    (152, 'Energy Hold - Block 152', 'Super Mushroom', 'Energy Hold'),
    (153, 'Energy Hold - Block 153', '50 Coins', 'Energy Hold'),
    (154, 'Energy Hold - Block 154', '10 Coins', 'Energy Hold'),
    (155, 'Energy Hold - Block 155', '50 Coins', 'Energy Hold'),
    (156, 'Energy Hold - Block 156', '1-Up Deluxe', 'Energy Hold'),
    (157, 'Energy Hold - Block 157', 'Hero Wear', 'Energy Hold'),
    (158, 'Energy Hold - Block 158', '50 Coins', 'Energy Hold'),
    (159, 'Energy Hold - Block 159', 'Supersyrup Jar', 'Energy Hold'),
    (160, 'Energy Hold - Block 160', '100 Coins', 'Energy Hold'),
    (161, 'Energy Hold - Block 161', '50 Coins', 'Energy Hold'),
    (162, 'Energy Hold - Block 162', 'Star Candy', 'Energy Hold'),
    (164, 'Energy Hold - Block 164', 'Supersyrup Jar', 'Energy Hold'),
    (165, 'Energy Hold - Block 165', '50 Coins', 'Energy Hold'),
    (166, 'Energy Hold - Block 166', '100 Coins', 'Energy Hold'),
    (167, 'Energy Hold - Block 167', 'Super Nut', 'Energy Hold'),
    (168, 'Energy Hold - Block 168', 'Delicious Gloves', 'Energy Hold'),
    (169, 'Energy Hold - Block 169', 'Retry Clock', 'Energy Hold'),
    (170, 'Energy Hold - Block 170', 'Super Nut', 'Energy Hold'),
    (171, 'Blubble Lake - Block 171', 'Super Nut', 'Blubble Lake'),
    (172, 'Blubble Lake - Brick 172', '50 Coins', 'Blubble Lake'),
    (173, 'Blubble Lake - Block 173', '1-Up Deluxe', 'Blubble Lake'),
    (174, 'Blubble Lake - Brick 174', '100 Coins', 'Blubble Lake'),
    (175, 'Blubble Lake - Brick 175', 'Fiery Drumstick', 'Blubble Lake'),
    (176, 'Blubble Lake - Block 176', 'Brawny Wear', 'Blubble Lake'),
    (177, 'Blubble Lake - Block 177', '250 Coins', 'Blubble Lake'),
    (178, 'Blubble Lake - Brick 178', '50 Coins', 'Blubble Lake'),
    (180, 'Blubble Lake - Bean 180', 'Heart Bean', 'Blubble Lake'),
    (181, 'Blubble Lake - Block 181', '50 Coins', 'Blubble Lake'),
    (182, 'Blubble Lake - Block 182', 'Super Mushroom', 'Blubble Lake'),
    (183, 'Blubble Lake - Brick 183', 'Rampage Shell', 'Blubble Lake'),
    (184, 'Blubble Lake - Brick 184', '10 Coins', 'Blubble Lake'),
    (185, 'Blubble Lake - Brick 185', 'Supersyrup Jar', 'Blubble Lake'),
    (186, 'Blubble Lake - Brick 186', 'Fury Fangs', 'Blubble Lake'),
    (188, 'Blubble Lake - Brick 188', 'Supersyrup Jar', 'Blubble Lake'),
    (189, 'Blubble Lake - Brick 189', '100 Coins', 'Blubble Lake'),
    (190, 'Blubble Lake - Block 190', 'Luxury Patch', 'Blubble Lake'),
    (191, 'Blubble Lake - Brick 191', '50 Coins', 'Blubble Lake'),
    (192, 'Blubble Lake - Block 192', 'Deluxe HP Socks', 'Blubble Lake'),
    (193, 'Blubble Lake - Block 193', 'Star Candy', 'Blubble Lake'),
    (195, 'Blubble Lake - Block 195', '100 Coins', 'Blubble Lake'),
    (196, 'Toad Town - Bean 196', 'Special Bean', 'Toad Town'),
    (197, 'Pump Works - Block 197', 'Star Candy', 'Pump Works'),
    (198, 'Pump Works - Block 198', 'Guardian Socks', 'Pump Works'),
    (199, 'Toad Town - Block 199', 'DX POW Gloves', 'Toad Town'),
    (200, 'Flab Zone - Block 200', '10 Coins', 'Flab Zone'),
    (201, 'Flab Zone - Block 201', 'Supersyrup Jar', 'Flab Zone'),
    (202, 'Flab Zone - Block 202', 'Ultra Nut', 'Flab Zone'),
    (203, 'Flab Zone - Block 203', 'EXP Socks', 'Flab Zone'),
    (204, 'Blubble Lake - Bean 204', 'Heart Bean', 'Blubble Lake'),
    (205, 'Blubble Lake - Bean 205', 'Heart Bean', 'Blubble Lake'),
    (206, 'Blubble Lake - Bean 206', 'Special Bean', 'Blubble Lake'),
    (207, 'Energy Hold - Bean 207', 'Heart Bean', 'Energy Hold'),
    (208, 'Energy Hold - Bean 208', 'Heart Bean', 'Energy Hold'),
    (209, 'Energy Hold - Bean 209', 'Special Bean', 'Energy Hold'),
    (210, 'Energy Hold - Block 210', '50 Coins', 'Energy Hold'),
    (211, 'Energy Hold - Block 211', '10 Coins', 'Energy Hold'),
    (212, 'Energy Hold - Block 212', '50 Coins', 'Energy Hold'),
    (213, 'Blubble Lake - Bean 213', 'Heart Bean', 'Blubble Lake'),
    (214, "Peach's Castle - Bean 214", 'Power Bean', "Peach's Castle"),
    (215, 'Blubble Lake - Bean 215', 'Special Bean', 'Blubble Lake'),
    (216, 'Blubble Lake - Bean 216', 'Heart Bean', 'Blubble Lake'),
    (217, 'Blubble Lake - Bean 217', 'Special Bean', 'Blubble Lake'),
    (218, 'Blubble Lake - Bean 218', 'Power Bean', 'Blubble Lake'),
    (219, 'Blubble Lake - Bean 219', 'Heart Bean', 'Blubble Lake'),
    (220, 'Blubble Lake - Bean 220', 'Special Bean', 'Blubble Lake'),
    (221, 'Blubble Lake - Bean 221', 'Power Bean', 'Blubble Lake'),
    (222, 'Energy Hold - Bean 222', 'Heart Bean', 'Energy Hold'),
    (223, 'Energy Hold - Bean 223', 'Heart Bean', 'Energy Hold'),
    (224, 'Energy Hold - Bean 224', 'Special Bean', 'Energy Hold'),
    (225, 'Energy Hold - Bean 225', 'Heart Bean', 'Energy Hold'),
    (226, 'Energy Hold - Bean 226', 'Heart Bean', 'Energy Hold'),
    (227, 'Energy Hold - Bean 227', 'Special Bean', 'Energy Hold'),
    (228, 'Energy Hold - Bean 228', 'Heart Bean', 'Energy Hold'),
    (229, 'Energy Hold - Bean 229', 'Heart Bean', 'Energy Hold'),
    (230, 'Energy Hold - Bean 230', 'Special Bean', 'Energy Hold'),
    (231, 'Toad Town - Bean 231', 'Heart Bean', 'Toad Town'),
    (232, 'Toad Town - Bean 232', 'Special Bean', 'Toad Town'),
    (233, 'Toad Town - Bean 233', 'Heart Bean', 'Toad Town'),
    (234, 'Toad Town - Bean 234', 'Special Bean', 'Toad Town'),
    (235, 'Toad Town - Bean 235', 'Heart Bean', 'Toad Town'),
    (236, 'Toad Town - Bean 236', 'Heart Bean', 'Toad Town'),
    (237, 'Toad Town - Bean 237', 'Special Bean', 'Toad Town'),
    (238, 'Toad Town - Bean 238', 'Heart Bean', 'Toad Town'),
    (239, 'Toad Town - Bean 239', 'Power Bean', 'Toad Town'),
    (240, 'Toad Town - Bean 240', 'Heart Bean', 'Toad Town'),
    (241, 'Toad Town - Bean 241', 'Heart Bean', 'Toad Town'),
    (242, 'Toad Town - Bean 242', 'Special Bean', 'Toad Town'),
    (243, 'Toad Town - Bean 243', 'Heart Bean', 'Toad Town'),
    (244, 'Toad Town - Bean 244', 'Power Bean', 'Toad Town'),
    (245, 'Toad Town - Bean 245', 'Special Bean', 'Toad Town'),
    (246, 'Toad Town - Bean 246', 'Heart Bean', 'Toad Town'),
    (247, 'Toad Town - Bean 247', 'Heart Bean', 'Toad Town'),
    (248, 'Pump Works - Block 248', 'Mushroom', 'Pump Works'),
    (249, 'Pump Works - Block 249', '10 Coins', 'Pump Works'),
    (250, 'Energy Hold - Bean 250', 'Heart Bean', 'Energy Hold'),
    (251, 'Energy Hold - Bean 251', 'Heart Bean', 'Energy Hold'),
    (252, 'Energy Hold - Bean 252', 'Special Bean', 'Energy Hold'),
    (253, 'Energy Hold - Bean 253', 'Heart Bean', 'Energy Hold'),
    (254, 'Energy Hold - Bean 254', 'Heart Bean', 'Energy Hold'),
    (255, 'Blubble Lake - Bean 255', 'Heart Bean', 'Blubble Lake'),
    (256, 'Plack Beach - Bean 256', 'Heart Bean', 'Plack Beach'),
    (257, 'Plack Beach - Bean 257', 'Special Bean', 'Plack Beach'),
    (258, 'Plack Beach - Bean 258', 'Heart Bean', 'Plack Beach'),
    (260, 'Plack Beach - Bean 260', 'Special Bean', 'Plack Beach'),
    (261, 'Plack Beach - Bean 261', 'Heart Bean', 'Plack Beach'),
    (262, 'Plack Beach - Bean 262', 'Heart Bean', 'Plack Beach'),
    (263, 'Plack Beach - Bean 263', 'Power Bean', 'Plack Beach'),
    (264, 'Plack Beach - Bean 264', 'Power Bean', 'Plack Beach'),
    (265, 'Plack Beach - Block 265', '50 Coins', 'Plack Beach'),
    (266, 'Bowser Castle - Bean 266', 'Heart Bean', 'Bowser Castle'),
    (267, 'Bowser Castle - Bean 267', 'Heart Bean', 'Bowser Castle'),
    (268, 'Bowser Castle - Bean 268', 'Special Bean', 'Bowser Castle'),
    (269, 'Bowser Castle - Bean 269', 'Heart Bean', 'Bowser Castle'),
    (270, 'Bowser Castle - Bean 270', 'Heart Bean', 'Bowser Castle'),
    (271, 'Bowser Castle - Bean 271', 'Special Bean', 'Bowser Castle'),
    (272, 'Bowser Castle - Bean 272', 'Heart Bean', 'Bowser Castle'),
    (273, 'Bowser Castle - Bean 273', 'Heart Bean', 'Bowser Castle'),
    (274, 'Toad Town - Bean 274', 'Special Bean', 'Toad Town'),
    (275, 'Toad Town - Bean 275', 'Heart Bean', 'Toad Town'),
    (276, 'Toad Town - Bean 276', 'Heart Bean', 'Toad Town'),
    (277, 'Toad Town - Block 277', 'Max Mushroom', 'Toad Town'),
    (278, 'Toad Town - Block 278', 'Budget Charm', 'Toad Town'),
    (279, 'Toad Town - Block 279', 'Max Nut', 'Toad Town'),
    (280, 'Toad Town - Block 280', '500 Coins', 'Toad Town'),
    (281, 'Toad Town - Block 281', 'KO Shell', 'Toad Town'),
    (282, 'Toad Town - Block 282', '1-Up Deluxe', 'Toad Town'),
    (283, 'Dimble Wood - Bean 283', 'Power Bean', 'Dimble Wood'),
    (285, 'Dimble Wood - Bean 285', 'Heart Bean', 'Dimble Wood'),
    (286, 'Dimble Wood - Bean 286', 'Special Bean', 'Dimble Wood'),
    (287, "Peach's Castle - Brick 287", 'Retry Clock', "Peach's Castle"),
    (288, 'Dimble Wood - Bean 288', 'Power Bean', 'Dimble Wood'),
    (289, 'Dimble Wood - Bean 289', 'Heart Bean', 'Dimble Wood'),
    (290, 'Dimble Wood - Bean 290', 'Special Bean', 'Dimble Wood'),
    (291, 'Dimble Wood - Bean 291', 'Heart Bean', 'Dimble Wood'),
    (292, 'Dimble Wood - Bean 292', 'Heart Bean', 'Dimble Wood'),
    (293, 'Dimble Wood - Bean 293', 'Special Bean', 'Dimble Wood'),
    (294, 'Dimble Wood - Bean 294', 'Heart Bean', 'Dimble Wood'),
    (295, 'Dimble Wood - Bean 295', 'Power Bean', 'Dimble Wood'),
    (296, 'Dimble Wood - Bean 296', 'Heart Bean', 'Dimble Wood'),
    (297, 'Dimble Wood - Bean 297', 'Special Bean', 'Dimble Wood'),
    (298, 'Dimble Wood - Bean 298', 'Heart Bean', 'Dimble Wood'),
    (299, 'Dimble Wood - Bean 299', 'Heart Bean', 'Dimble Wood'),
    (300, 'Dimble Wood - Bean 300', 'Power Bean', 'Dimble Wood'),
    (301, 'Dimble Wood - Bean 301', 'Special Bean', 'Dimble Wood'),
    (302, 'Plack Beach - Block 302', '250 Coins', 'Plack Beach'),
    (303, 'Plack Beach - Block 303', 'Mushroom Gloves', 'Plack Beach'),
    (304, 'Plack Beach - Block 304', 'Star Candy', 'Plack Beach'),
    (305, 'Plack Beach - Block 305', '50 Coins', 'Plack Beach'),
    (306, 'Plack Beach - Block 306', 'Flower Gloves', 'Plack Beach'),
    (307, 'Plack Beach - Bean 307', 'Special Bean', 'Plack Beach'),
    (308, "Peach's Castle - Block 308", 'Ultra Mushroom', "Peach's Castle"),
    (309, "Peach's Castle - Block 309", '100 Coins', "Peach's Castle"),
    (310, 'Airway - Bean 310', 'Special Bean', 'Airway'),
    (311, 'Airway - Bean 311', 'Heart Bean', 'Airway'),
    (312, 'Airway - Block 312', '50 Coins', 'Airway'),
    (314, 'Airway - Block 314', '100 Coins', 'Airway'),
    (315, 'Airway - Block 315', '1-Up Deluxe', 'Airway'),
    (316, 'Airway - Block 316', 'Ultra Mushroom', 'Airway'),
    (317, 'Airway - Block 317', '50 Coins', 'Airway'),
    (318, 'Airway - Block 318', '100 Coins', 'Airway'),
    (319, 'Airway - Block 319', 'Supersyrup Jar', 'Airway'),
    (320, 'Airway - Block 320', '500 Coins', 'Airway'),
    (321, 'Airway - Block 321', '50 Coins', 'Airway'),
    (322, 'Airway - Block 322', 'Retry Clock', 'Airway'),
    (323, 'Airway - Block 323', 'Ultra Nut', 'Airway'),
    (324, 'Airway - Block 324', '500 Coins', 'Airway'),
    (325, 'Dimble Wood - Bean 325', 'Heart Bean', 'Dimble Wood'),
    (326, 'Dimble Wood - Bean 326', 'Special Bean', 'Dimble Wood'),
    (327, 'Airway - Block 327', '50 Coins', 'Airway'),
    (328, 'Airway - Block 328', 'King Wear', 'Airway'),
    (329, 'Airway - Block 329', '1-Up Deluxe', 'Airway'),
    (330, 'Airway - Block 330', '100 Coins', 'Airway'),
    (331, 'Airway - Block 331', '250 Coins', 'Airway'),
    (332, 'Airway - Block 332', 'Guardian Socks', 'Airway'),
    (333, 'Airway - Block 333', '100 Coins', 'Airway'),
    (334, 'Airway - Block 334', '50 Coins', 'Airway'),
    (335, 'Airway - Block 335', 'Ultra Mushroom', 'Airway'),
    (336, 'Bowser Path - Block 336', 'Max Nut', 'Bowser Path'),
    (337, 'Bowser Path - Block 337', '300 Coins', 'Bowser Path'),
    (338, 'Bowser Path - Block 338', 'Giant Shell', 'Bowser Path'),
    (339, 'Dimble Wood - Bean 339', 'Special Bean', 'Dimble Wood'),
    (340, 'Dimble Wood - Bean 340', 'Heart Bean', 'Dimble Wood'),
    (341, 'Dimble Wood - Bean 341', 'Heart Bean', 'Dimble Wood'),
    (343, 'Dimble Wood - Bean 343', 'Heart Bean', 'Dimble Wood'),
    (344, 'Bowser Castle - Bean 344', 'Power Bean', 'Bowser Castle'),
    (345, 'Bowser Castle - Bean 345', 'Heart Bean', 'Bowser Castle'),
    (346, 'Bowser Castle - Bean 346', 'Heart Bean', 'Bowser Castle'),
    (347, 'Bowser Castle - Bean 347', 'Special Bean', 'Bowser Castle'),
    (348, 'Bowser Castle - Bean 348', 'Special Bean', 'Bowser Castle'),
    (349, 'Bowser Castle - Bean 349', 'Heart Bean', 'Bowser Castle'),
    (350, 'Bowser Castle - Bean 350', 'Power Bean', 'Bowser Castle'),
    (351, 'Plack Beach - Bean 351', 'Power Bean', 'Plack Beach'),
    (352, 'Bowser Castle - Brick 352', 'TNT Drumstick', 'Bowser Castle'),
    (353, 'Bowser Castle - Brick 353', 'Burning Fangs', 'Bowser Castle'),
    (354, 'Bowser Castle - Brick 354', 'Star Candy', 'Bowser Castle'),
    (355, 'Bowser Castle - Brick 355', '100 Coins', 'Bowser Castle'),
    (356, 'Bowser Castle - Brick 356', 'Supersyrup Jar', 'Bowser Castle'),
    (357, 'Bowser Castle - Brick 357', '10 Coins', 'Bowser Castle'),
    (358, 'Bowser Castle - Brick 358', 'TNT Drumstick', 'Bowser Castle'),
    (359, 'Bowser Castle - Brick 359', 'Supersyrup Jar', 'Bowser Castle'),
    (360, 'Bowser Castle - Brick 360', '50 Coins', 'Bowser Castle'),
    (361, 'Bowser Castle - Brick 361', '10 Coins', 'Bowser Castle'),
    (362, 'Bowser Castle - Brick 362', '50 Coins', 'Bowser Castle'),
    (363, 'Bowser Castle - Brick 363', 'Supersyrup Jar', 'Bowser Castle'),
    (365, 'Bowser Castle - Brick 365', 'TNT Drumstick', 'Bowser Castle'),
    (366, 'Bowser Castle - Brick 366', '50 Coins', 'Bowser Castle'),
    (367, 'Bowser Castle - Brick 367', '100 Coins', 'Bowser Castle'),
    (368, 'Bowser Castle - Brick 368', '100 Coins', 'Bowser Castle'),
    (369, 'Bowser Castle - Brick 369', '10 Coins', 'Bowser Castle'),
    (370, 'Bowser Castle - Bean 370', 'Heart Bean', 'Bowser Castle'),
    (371, 'Bowser Castle - Bean 371', 'Heart Bean', 'Bowser Castle'),
    (372, 'Bowser Castle - Bean 372', 'Special Bean', 'Bowser Castle'),
    (373, 'Bowser Castle - Bean 373', 'Heart Bean', 'Bowser Castle'),
    (374, 'Bowser Castle - Bean 374', 'Heart Bean', 'Bowser Castle'),
    (375, 'Bowser Castle - Bean 375', 'Heart Bean', 'Bowser Castle'),
    (376, 'Bowser Castle - Bean 376', 'Heart Bean', 'Bowser Castle'),
    (377, 'Bowser Castle - Bean 377', 'Special Bean', 'Bowser Castle'),
    (378, 'Bowser Castle - Bean 378', 'Heart Bean', 'Bowser Castle'),
    (379, 'Bowser Castle - Bean 379', 'Special Bean', 'Bowser Castle'),
    (380, 'Bowser Castle - Bean 380', 'Heart Bean', 'Bowser Castle'),
    (381, 'Bowser Castle - Bean 381', 'Heart Bean', 'Bowser Castle'),
    (382, 'Bowser Castle - Bean 382', 'Power Bean', 'Bowser Castle'),
    (383, 'Bowser Castle - Bean 383', 'Heart Bean', 'Bowser Castle'),
    (384, 'Bowser Castle - Bean 384', 'Special Bean', 'Bowser Castle'),
    (385, 'Bowser Castle - Bean 385', 'Heart Bean', 'Bowser Castle'),
    (386, 'Bowser Castle - Bean 386', 'Heart Bean', 'Bowser Castle'),
    (387, 'Bowser Castle - Bean 387', 'Special Bean', 'Bowser Castle'),
    (388, 'Bowser Castle - Bean 388', 'Heart Bean', 'Bowser Castle'),
    (389, 'Bowser Castle - Bean 389', 'Heart Bean', 'Bowser Castle'),
    (390, 'Bowser Castle - Block 390', '50 Coins', 'Bowser Castle'),
    (391, 'Tunnel - Brick 391', '10 Coins', 'Tunnel'),
    (392, 'Tunnel - Brick 392', 'Special Fangs', 'Tunnel'),
    (393, 'Tunnel - Brick 393', '5 Coins', 'Tunnel'),
    (396, 'Tunnel - Brick 396', '10 Coins', 'Tunnel'),
    (397, 'Tunnel - Brick 397', 'Supersyrup Jar', 'Tunnel'),
    (398, 'Tunnel - Brick 398', '10 Coins', 'Tunnel'),
    (399, 'Tunnel - Brick 399', '10 Coins', 'Tunnel'),
    (400, 'Tunnel - Brick 400', '50 Coins', 'Tunnel'),
    (401, 'Tunnel - Brick 401', 'Cheap Ring', 'Tunnel'),
    (402, "Peach's Castle - Brick 402", '100 Coins', "Peach's Castle"),
    (403, "Peach's Castle - Brick 403", 'TNT Drumstick', "Peach's Castle"),
    (404, "Peach's Castle - Brick 404", '100 Coins', "Peach's Castle"),
    (405, "Peach's Castle - Brick 405", '50 Coins', "Peach's Castle"),
    (406, "Peach's Castle - Brick 406", 'Ultrasyrup Jar', "Peach's Castle"),
    (407, "Peach's Castle - Brick 407", 'TNT Drumstick', "Peach's Castle"),
    (408, "Peach's Castle - Brick 408", 'Economy Ring', "Peach's Castle"),
    (409, "Peach's Castle - Brick 409", '50 Coins', "Peach's Castle"),
    (410, "Peach's Castle - Brick 410", 'Supersyrup Jar', "Peach's Castle"),
    (411, "Peach's Castle - Brick 411", 'Retry Clock', "Peach's Castle"),
    (412, "Peach's Castle - Brick 412", 'Wicked Shell', "Peach's Castle"),
    (414, "Peach's Castle - Brick 414", 'Power Band +', "Peach's Castle"),
    (415, "Peach's Castle - Brick 415", '100 Coins', "Peach's Castle"),
    (416, "Peach's Castle - Brick 416", '50 Coins', "Peach's Castle"),
    (417, "Peach's Castle - Brick 417", 'Max Syrup Jar', "Peach's Castle"),
    (418, "Peach's Castle - Brick 418", '50 Coins', "Peach's Castle"),
    (419, "Peach's Castle - Brick 419", '50 Coins', "Peach's Castle"),
    (420, "Peach's Castle - Brick 420", '100 Coins', "Peach's Castle"),
    (421, "Peach's Castle - Brick 421", 'TNT Drumstick', "Peach's Castle"),
    (422, "Peach's Castle - Brick 422", '100 Coins', "Peach's Castle"),
    (423, "Peach's Castle - Brick 423", '50 Coins', "Peach's Castle"),
    (424, "Peach's Castle - Brick 424", 'Stamina Band', "Peach's Castle"),
    (425, "Peach's Castle - Brick 425", 'Star Candy', "Peach's Castle"),
    (426, "Peach's Castle - Brick 426", '100 Coins', "Peach's Castle"),
    (427, "Peach's Castle - Brick 427", 'Max Syrup Jar', "Peach's Castle"),
    (428, "Peach's Castle - Brick 428", '50 Coins', "Peach's Castle"),
    (429, "Peach's Castle - Brick 429", 'Restore Ring', "Peach's Castle"),
    (430, "Peach's Castle - Brick 430", '100 Coins', "Peach's Castle"),
    (431, "Peach's Castle - Brick 431", 'Retry Clock', "Peach's Castle"),
    (432, "Peach's Castle - Brick 432", '100 Coins', "Peach's Castle"),
    (433, "Peach's Castle - Brick 433", 'TNT Drumstick', "Peach's Castle"),
    (434, "Peach's Castle - Brick 434", '100 Coins', "Peach's Castle"),
    (435, "Peach's Castle - Block 435", 'Retry Clock', "Peach's Castle"),
    (436, "Peach's Castle - Brick 436", 'TNT Drumstick', "Peach's Castle"),
    (437, "Peach's Castle - Brick 437", 'Ultrasyrup Jar', "Peach's Castle"),
    (438, "Peach's Castle - Brick 438", 'Star Candy', "Peach's Castle"),
    (442, "Peach's Castle - Block 442", 'Supersyrup Jar', "Peach's Castle"),
    (443, "Peach's Castle - Block 443", 'Retry Clock', "Peach's Castle"),
    (444, "Peach's Castle - Block 444", '10 Coins', "Peach's Castle"),
    (445, "Peach's Castle - Block 445", '100 Coins', "Peach's Castle"),
    (446, "Peach's Castle - Block 446", '100 Coins', "Peach's Castle"),
    (447, "Peach's Castle - Bean 447", 'Power Bean', "Peach's Castle"),
    (448, "Peach's Castle - Block 448", 'Max Nut', "Peach's Castle"),
    (449, "Peach's Castle - Block 449", 'Ultra Mushroom', "Peach's Castle"),
    (450, "Peach's Castle - Block 450", '50 Coins', "Peach's Castle"),
    (451, "Peach's Castle - Block 451", '1-Up Deluxe', "Peach's Castle"),
    (452, 'Plack Beach - Bean 452', 'Power Bean', 'Plack Beach'),
    (453, "Peach's Castle - Block 453", '50 Coins', "Peach's Castle"),
    (454, "Peach's Castle - Block 454", 'DX POW Gloves', "Peach's Castle"),
    (455, "Peach's Castle - Block 455", 'Max Syrup Jar', "Peach's Castle"),
    (456, "Peach's Castle - Bean 456", 'Special Bean', "Peach's Castle"),
    (457, "Peach's Castle - Bean 457", 'Heart Bean', "Peach's Castle"),
    (458, "Peach's Castle - Bean 458", 'Heart Bean', "Peach's Castle"),
    (459, "Peach's Castle - Block 459", '500 Coins', "Peach's Castle"),
    (460, "Peach's Castle - Block 460", 'Surprising Socks', "Peach's Castle"),
    (461, "Peach's Castle - Block 461", 'Star Candy', "Peach's Castle"),
    (462, "Peach's Castle - Block 462", '100 Coins', "Peach's Castle"),
    (463, "Peach's Castle - Bean 463", 'Power Bean', "Peach's Castle"),
    (464, "Peach's Castle - Bean 464", 'Special Bean', "Peach's Castle"),
    (465, "Peach's Castle - Bean 465", 'Power Bean', "Peach's Castle"),
    (466, 'Toad Town - Block 466', '100 Coins', 'Toad Town'),
    (467, "Peach's Castle - Bean 467", 'Special Bean', "Peach's Castle"),
    (468, "Peach's Castle - Bean 468", 'Heart Bean', "Peach's Castle"),
    (469, "Peach's Castle - Bean 469", 'Special Bean', "Peach's Castle"),
    (470, "Peach's Castle - Bean 470", 'Heart Bean', "Peach's Castle"),
    (471, 'Tower of Yikk - Brick 471', '100 Coins', 'Tower of Yikk'),
    (472, 'Tower of Yikk - Brick 472', 'Star Candy', 'Tower of Yikk'),
    (473, 'Plack Beach - Bean 473', 'Power Bean', 'Plack Beach'),
    (474, 'Bowser Path - Bean 474', 'Special Bean', 'Bowser Path'),
    (475, 'Bowser Path - Bean 475', 'Heart Bean', 'Bowser Path'),
    (476, 'Bowser Path - Bean 476', 'Special Bean', 'Bowser Path'),
    (477, 'Plack Beach - Bean 477', 'Heart Bean', 'Plack Beach'),
    (478, 'Plack Beach - Bean 478', 'Heart Bean', 'Plack Beach'),
    (479, 'Plack Beach - Bean 479', 'Special Bean', 'Plack Beach'),
    (480, 'Bowser Path - Bean 480', 'Power Bean', 'Bowser Path'),
    (481, 'Bumpsy Plains - Bean 481', 'Heart Bean', 'Bumpsy Plains'),
    (482, 'Bumpsy Plains - Bean 482', 'Heart Bean', 'Bumpsy Plains'),
    (483, 'Bumpsy Plains - Bean 483', 'Power Bean', 'Bumpsy Plains'),
    (484, 'Bowser Path - Bean 484', 'Heart Bean', 'Bowser Path'),
    (486, 'Bowser Path - Bean 486', 'Heart Bean', 'Bowser Path'),
    (487, 'Bowser Path - Bean 487', 'Heart Bean', 'Bowser Path'),
    (488, 'Bowser Castle - Brick 488', 'Retry Clock', 'Bowser Castle'),
    (489, 'Bowser Castle - Brick 489', '50 Coins', 'Bowser Castle'),
    (490, 'Bowser Castle - Brick 490', 'Flashy Fangs', 'Bowser Castle'),
    (491, 'Cavi Cape - Brick 491', '10 Coins', 'Cavi Cape'),
    (492, 'Cavi Cape - Brick 492', 'Ironclad Shell', 'Cavi Cape'),
    (493, 'Cavi Cape - Brick 493', 'Hot Drumstick', 'Cavi Cape'),
    (494, 'Cavi Cape - Brick 494', 'Red-hot Fangs', 'Cavi Cape'),
    (495, 'Cavi Cape - Brick 495', 'Judge Shell', 'Cavi Cape'),
    (496, 'Cavi Cape - Bean 496', 'Power Bean', 'Cavi Cape'),
    (497, 'Cavi Cape - Bean 497', 'Heart Bean', 'Cavi Cape'),
    (498, 'Cavi Cape - Bean 498', 'Heart Bean', 'Cavi Cape'),
    (499, 'Cavi Cape - Bean 499', 'Special Bean', 'Cavi Cape'),
    (500, 'Cavi Cape - Bean 500', 'Power Bean', 'Cavi Cape'),
    (501, 'Cavi Cape - Bean 501', 'Special Bean', 'Cavi Cape'),
    (502, 'Cavi Cape - Bean 502', 'Power Bean', 'Cavi Cape'),
    (503, 'Cavi Cape - Bean 503', 'Heart Bean', 'Cavi Cape'),
    (504, 'Cavi Cape - Bean 504', 'Heart Bean', 'Cavi Cape'),
    (505, 'Cavi Cape - Bean 505', 'Heart Bean', 'Cavi Cape'),
    (506, "Peach's Castle - Block 506", '500 Coins', "Peach's Castle"),
    (507, "Peach's Castle - Block 507", '100 Coins', "Peach's Castle"),
    (508, "Peach's Castle - Block 508", '50 Coins', "Peach's Castle"),
    (509, "Peach's Castle - Block 509", 'Max Syrup Jar', "Peach's Castle"),
    (513, 'Airway - Block 513', '1-Up Deluxe', 'Airway'),
    (514, 'Airway - Block 514', 'Supersyrup Jar', 'Airway'),
    (515, 'Airway - Block 515', '100 Coins', 'Airway'),
    (516, 'Airway - Bean 516', 'Heart Bean', 'Airway'),
    (517, 'Airway - Bean 517', 'Special Bean', 'Airway'),
    (518, 'Airway - Bean 518', 'Heart Bean', 'Airway'),
    (519, 'Airway - Bean 519', 'Power Bean', 'Airway'),
    (520, 'Airway - Block 520', '500 Coins', 'Airway'),
    (521, 'Airway - Block 521', '100 Coins', 'Airway'),
    (522, 'Airway - Block 522', '50 Coins', 'Airway'),
    (523, 'Airway - Block 523', '50 Coins', 'Airway'),
    (524, 'Airway - Block 524', '100 Coins', 'Airway'),
    (525, 'Airway - Block 525', '50 Coins', 'Airway'),
    (526, 'Airway - Block 526', '1-Up Deluxe', 'Airway'),
    (527, 'Airway - Block 527', 'Max Nut', 'Airway'),
    (528, 'Airway - Block 528', 'Star Candy', 'Airway'),
    (529, 'Airway - Block 529', '500 Coins', 'Airway'),
    (530, 'Airway - Block 530', '100 Coins', 'Airway'),
    (531, 'Airway - Block 531', '50 Coins', 'Airway'),
    (532, 'Airway - Block 532', '50 Coins', 'Airway'),
    (533, 'Airway - Block 533', 'Rugged Socks', 'Airway'),
    (534, 'Airway - Block 534', 'Retry Clock', 'Airway'),
    (535, 'Airway - Block 535', '1-Up Deluxe', 'Airway'),
    (536, 'Airway - Block 536', 'Max Nut', 'Airway'),
    (537, 'Airway - Block 537', 'Supersyrup Jar', 'Airway'),
    (538, 'Airway - Block 538', 'Star Wear', 'Airway'),
    (539, 'Airway - Bean 539', 'Special Bean', 'Airway'),
    (540, 'Airway - Bean 540', 'Special Bean', 'Airway'),
    (541, 'Trash Pit - Block 541', '25 Coins', 'Trash Pit'),
    (542, 'Trash Pit - Block 542', 'Syrup Jar', 'Trash Pit'),
    (543, 'Cavi Cape - Bean 543', 'Heart Bean', 'Cavi Cape'),
    (544, "Peach's Castle - Block 544", '1 Coins', "Peach's Castle"),
    (545, "Peach's Castle - Block 545", '5 Coins', "Peach's Castle"),
    (546, "Peach's Castle - Block 546", '10 Coins', "Peach's Castle"),
    (547, "Peach's Castle - Block 547", '1 Coins', "Peach's Castle"),
    (548, "Peach's Castle - Block 548", '5 Coins', "Peach's Castle"),
    (549, 'Trash Pit - Block 549', '10 Coins', 'Trash Pit'),
    (550, 'Trash Pit - Block 550', 'Mushroom', 'Trash Pit'),
    (551, 'Trash Pit - Block 551', '10 Coins', 'Trash Pit'),
    (552, 'Trash Pit - Block 552', '5 Coins', 'Trash Pit'),
    (553, 'Trash Pit - Block 553', '5 Coins', 'Trash Pit'),
    (554, 'Trash Pit - Block 554', 'Mushroom', 'Trash Pit'),
    (555, 'Trash Pit - Block 555', '1-Up Mushroom', 'Trash Pit'),
    (556, 'Trash Pit - Block 556', 'Mushroom', 'Trash Pit'),
    (557, 'Trash Pit - Block 557', 'Syrup Jar', 'Trash Pit'),
    (558, "Peach's Castle - Brick 558", '100 Coins', "Peach's Castle"),
    (559, "Peach's Castle - Brick 559", 'TNT Drumstick', "Peach's Castle"),
    (560, "Peach's Castle - Brick 560", 'Refreshing Herb', "Peach's Castle"),
    (561, "Peach's Castle - Brick 561", 'Max Syrup Jar', "Peach's Castle"),
    (562, "Peach's Castle - Brick 562", '100 Coins', "Peach's Castle"),
    (563, "Peach's Castle - Brick 563", 'Star Candy', "Peach's Castle"),
    (564, "Peach's Castle - Brick 564", '100 Coins', "Peach's Castle"),
    (565, "Peach's Castle - Brick 565", 'Max Syrup Jar', "Peach's Castle"),
    (566, "Peach's Castle - Brick 566", '100 Coins', "Peach's Castle"),
    (567, "Peach's Castle - Brick 567", 'TNT Drumstick', "Peach's Castle"),
    (568, "Peach's Castle - Brick 568", 'Retry Clock', "Peach's Castle"),
    (569, "Peach's Castle - Brick 569", 'Star Candy', "Peach's Castle"),
    (570, "Peach's Castle - Brick 570", 'Special Fangs X', "Peach's Castle"),
    (572, "Peach's Castle - Brick 572", '100 Coins', "Peach's Castle"),
    (573, "Peach's Castle - Brick 573", '50 Coins', "Peach's Castle"),
    (574, "Peach's Castle - Brick 574", '100 Coins', "Peach's Castle"),
    (575, "Peach's Castle - Brick 575", 'Star Candy', "Peach's Castle"),
    (576, "Peach's Castle - Brick 576", '100 Coins', "Peach's Castle"),
    (578, "Peach's Castle - Block 578", '50 Coins', "Peach's Castle"),
    (579, "Peach's Castle - Block 579", 'Max Nut', "Peach's Castle"),
    (580, "Peach's Castle - Block 580", '500 Coins', "Peach's Castle"),
    (581, "Peach's Castle - Block 581", 'Max Syrup Jar', "Peach's Castle"),
    (582, "Peach's Castle - Block 582", 'Max Mushroom', "Peach's Castle"),
    (583, "Peach's Castle - Block 583", '100 Coins', "Peach's Castle"),
    (584, "Peach's Castle - Block 584", 'Star Candy', "Peach's Castle"),
    (585, "Peach's Castle - Block 585", '100 Coins', "Peach's Castle"),
    (586, "Peach's Castle - Block 586", 'D-Star Wear', "Peach's Castle"),
    (587, "Peach's Castle - Brick 587", 'Ultrasyrup Jar', "Peach's Castle"),
    (588, "Peach's Castle - Brick 588", '100 Coins', "Peach's Castle"),
    (591, 'Bowser Path - Block 591', 'Max Nut', 'Bowser Path'),
    (592, 'Plack Beach - Bean 592', 'Heart Bean', 'Plack Beach'),
    (593, 'Plack Beach - Bean 593', 'Special Bean', 'Plack Beach'),
    (598, 'Dimble Wood - Grass 598', '10 Coins', 'Dimble Wood'),
    (599, 'Dimble Wood - Bean 599', 'Heart Bean', 'Dimble Wood'),
    (600, "Peach's Castle - Bean 600", 'Heart Bean', "Peach's Castle"),
    (601, 'Dimble Wood - Bean 601', 'Heart Bean', 'Dimble Wood'),
    (603, 'Toad Town - Bean 603', 'Power Bean', 'Toad Town'),
    (604, 'Toad Town - Bean 604', 'Power Bean', 'Toad Town'),
    (605, 'Bowser Castle - Bean 605', 'Power Bean', 'Bowser Castle'),
    (606, 'Dimble Wood - Grass 606', '5 Coins', 'Dimble Wood'),
    (607, 'Bowser Path - Bean 607', 'Power Bean', 'Bowser Path'),
    (608, 'Bowser Castle - Bean 608', 'Power Bean', 'Bowser Castle'),
    (609, 'Bowser Path - Bean 609', 'Power Bean', 'Bowser Path'),
    (610, "Peach's Castle - Bean 610", 'Heart Bean', "Peach's Castle"),
    (611, "Peach's Castle - Bean 611", 'Heart Bean', "Peach's Castle"),
    (612, 'Bowser Path - Block 612', 'Bye-Bye Gloves', 'Bowser Path'),
    (613, 'Bowser Castle - Bean 613', 'Power Bean', 'Bowser Castle'),
    (614, 'Pump Works - Block 614', '10 Coins', 'Pump Works'),
    (615, 'Dimble Wood - Block 615', '1-Up Deluxe', 'Dimble Wood'),
    (616, 'Dimble Wood - Block 616', 'Star Candy', 'Dimble Wood'),
    (617, 'Dimble Wood - Block 617', 'Max Mushroom', 'Dimble Wood'),
    (618, 'Dimble Wood - Block 618', '250 Coins', 'Dimble Wood'),
    (619, 'Dimble Wood - Block 619', 'DX SP Socks', 'Dimble Wood'),
    (620, 'Dimble Wood - Block 620', '100 Coins', 'Dimble Wood'),
    (621, 'Pump Works - Block 621', '100 Coins', 'Pump Works'),
    (622, 'Pump Works - Block 622', '1-Up Deluxe', 'Pump Works'),
    (623, 'Blubble Lake - Brick 623', '10 Coins', 'Blubble Lake'),
    (624, 'Blubble Lake - Brick 624', '100 Coins', 'Blubble Lake'),
    (625, 'Blubble Lake - Brick 625', 'Hot Drumstick', 'Blubble Lake'),
    (626, 'Blubble Lake - Brick 626', '50 Coins', 'Blubble Lake'),
    (627, 'Blubble Lake - Brick 627', 'Supersyrup Jar', 'Blubble Lake'),
    (628, 'Energy Hold - Block 628', 'Refreshing Herb', 'Energy Hold'),
    (629, 'Energy Hold - Block 629', '1-Up Deluxe', 'Energy Hold'),
    (630, 'Energy Hold - Block 630', 'Super Mushroom', 'Energy Hold'),
    (631, 'Energy Hold - Block 631', 'Super Nut', 'Energy Hold'),
    (632, 'Cavi Cape - Brick 632', 'Hot Drumstick', 'Cavi Cape'),
    (633, 'Cavi Cape - Brick 633', '5 Coins', 'Cavi Cape'),
    (634, 'Cavi Cape - Brick 634', '5 Coins', 'Cavi Cape'),
    (635, 'Cavi Cape - Brick 635', '10 Coins', 'Cavi Cape'),
    (637, 'Plack Beach - Brick 637', 'Hot Drumstick', 'Plack Beach'),
    (638, 'Plack Beach - Brick 638', '10 Coins', 'Plack Beach'),
    (639, 'Plack Beach - Brick 639', 'Hot Drumstick', 'Plack Beach'),
    (640, 'Plack Beach - Brick 640', '5 Coins', 'Plack Beach'),
    (641, 'Plack Beach - Brick 641', 'Hot Drumstick', 'Plack Beach'),
    (642, 'Plack Beach - Brick 642', 'Hot Drumstick', 'Plack Beach'),
    (643, "Peach's Castle - Bean 643", 'Heart Bean', "Peach's Castle"),
    (644, 'Dimble Wood - Grass 644', '1 Coins', 'Dimble Wood'),
    (648, 'Dimble Wood - Grass 648', '1 Coins', 'Dimble Wood'),
    (650, 'Dimble Wood - Grass 650', '1 Coins', 'Dimble Wood'),
    (655, 'Dimble Wood - Grass 655', '1 Coins', 'Dimble Wood'),
    (662, 'Dimble Wood - Grass 662', '1 Coins', 'Dimble Wood'),
    (663, 'Dimble Wood - Grass 663', '1 Coins', 'Dimble Wood'),
    (667, 'Dimble Wood - Grass 667', '1 Coins', 'Dimble Wood'),
    (702, 'Dimble Wood - Grass 702', '1 Coins', 'Dimble Wood'),
    (704, 'Plack Beach - Block 704', 'Ultra Mushroom', 'Plack Beach'),
    (705, 'Plack Beach - Block 705', '10 Coins', 'Plack Beach'),
    (706, 'Bumpsy Plains - Grass 706', '1 Coins', 'Bumpsy Plains'),
    (708, 'Bumpsy Plains - Grass 708', '1 Coins', 'Bumpsy Plains'),
    (709, 'Bumpsy Plains - Grass 709', '5 Coins', 'Bumpsy Plains'),
    (710, 'Toad Town - Bean 710', 'Power Bean', 'Toad Town'),
    (711, 'Bumpsy Plains - Grass 711', '5 Coins', 'Bumpsy Plains'),
    (714, 'Bumpsy Plains - Grass 714', '1 Coins', 'Bumpsy Plains'),
    (722, 'Bumpsy Plains - Grass 722', '10 Coins', 'Bumpsy Plains'),
    (724, 'Dimble Wood - Bean 724', 'Heart Bean', 'Dimble Wood'),
    (725, 'Dimble Wood - Bean 725', 'Heart Bean', 'Dimble Wood'),
    (726, 'Dimble Wood - Block 726', '1-Up Deluxe', 'Dimble Wood'),
    (734, 'Toad Town - Block 734', 'Thrift Charm', 'Toad Town'),
    (735, 'Toad Town - Block 735', '100 Coins', 'Toad Town'),
    (737, 'Blubble Lake - Brick 737', '50 Coins', 'Blubble Lake'),
    (738, 'Blubble Lake - Brick 738', '50 Coins', 'Blubble Lake'),
    (739, 'Bowser Castle - Brick 739', '10 Coins', 'Bowser Castle'),
    (740, 'Bowser Castle - Brick 740', '10 Coins', 'Bowser Castle'),
    (741, "Peach's Castle - Brick 741", 'Ultrasyrup Jar', "Peach's Castle"),
    (742, "Peach's Castle - Bean 742", 'Heart Bean', "Peach's Castle"),
    (743, 'Bowser Path - Bean 743', 'Special Bean', 'Bowser Path'),
    (745, 'Plack Beach - Block 745', 'Max Nut', 'Plack Beach'),
    (746, 'Plack Beach - Block 746', 'Star Candy', 'Plack Beach'),
    (747, 'Bumpsy Plains - Block 747', 'Heroic Patch', 'Bumpsy Plains'),
    (748, 'Toad Town - Block 748', '100 Coins', 'Toad Town'),
    (749, 'Toad Town - Block 749', 'Star Candy', 'Toad Town'),
    (750, 'Toad Town - Block 750', '50 Coins', 'Toad Town'),
    (751, 'Toad Town - Block 751', 'Ultra Nut', 'Toad Town'),
    (752, "Peach's Castle - Block 752", '100 Coins', "Peach's Castle"),
    (753, "Peach's Castle - Block 753", '100 Coins', "Peach's Castle"),
    (754, "Peach's Castle - Brick 754", '100 Coins', "Peach's Castle"),
    (755, "Peach's Castle - Brick 755", '100 Coins', "Peach's Castle"),
    (756, 'Cavi Cape - Brick 756', 'Hot Drumstick', 'Cavi Cape'),
    (757, "Peach's Castle - Brick 757", '50 Coins', "Peach's Castle"),
]

# (rang de bit dans Exxx, nom de location, item d'origine, zone)
# Une piece d'attaque ; le rang tient lieu d'identifiant.
ATTACK_PIECES = [
    (1792, 'Trash Pit - Green Shell Piece 1', 'Green Shell Piece', 'Trash Pit'),
    (1793, 'Trash Pit - Green Shell Piece 2', 'Green Shell Piece', 'Trash Pit'),
    (1794, 'Trash Pit - Green Shell Piece 3', 'Green Shell Piece', 'Trash Pit'),
    (1795, 'Trash Pit - Green Shell Piece 4', 'Green Shell Piece', 'Trash Pit'),
    (1796, 'Trash Pit - Green Shell Piece 5', 'Green Shell Piece', 'Trash Pit'),
    (1797, 'Trash Pit - Green Shell Piece 6', 'Green Shell Piece', 'Trash Pit'),
    (1798, 'Trash Pit - Green Shell Piece 7', 'Green Shell Piece', 'Trash Pit'),
    (1799, 'Trash Pit - Green Shell Piece 8', 'Green Shell Piece', 'Trash Pit'),
    (1800, 'Trash Pit - Green Shell Piece 9', 'Green Shell Piece', 'Trash Pit'),
    (1801, 'Trash Pit - Green Shell Piece 10', 'Green Shell Piece', 'Trash Pit'),
    (1865, 'Pump Works - Fire Flower Piece 4', 'Fire Flower Piece', 'Pump Works'),
    (1876, 'Pump Works - Fire Flower Piece 7', 'Fire Flower Piece', 'Pump Works'),
    (1879, 'Pump Works - Fire Flower Piece 1', 'Fire Flower Piece', 'Pump Works'),
    (1880, 'Pump Works - Fire Flower Piece 2', 'Fire Flower Piece', 'Pump Works'),
    (1881, 'Pump Works - Fire Flower Piece 3', 'Fire Flower Piece', 'Pump Works'),
    (1882, 'Pump Works - Fire Flower Piece 5', 'Fire Flower Piece', 'Pump Works'),
    (1883, 'Pump Works - Fire Flower Piece 6', 'Fire Flower Piece', 'Pump Works'),
    (1884, 'Pump Works - Fire Flower Piece 8', 'Fire Flower Piece', 'Pump Works'),
    (1885, 'Pump Works - Fire Flower Piece 9', 'Fire Flower Piece', 'Pump Works'),
    (1886, 'Pump Works - Fire Flower Piece 10', 'Fire Flower Piece', 'Pump Works'),
    (1900, 'Plack Beach - Spin Pipe Piece 1', 'Spin Pipe Piece', 'Plack Beach'),
    (1901, 'Plack Beach - Spin Pipe Piece 2', 'Spin Pipe Piece', 'Plack Beach'),
    (1902, 'Plack Beach - Spin Pipe Piece 3', 'Spin Pipe Piece', 'Plack Beach'),
    (1903, 'Plack Beach - Spin Pipe Piece 4', 'Spin Pipe Piece', 'Plack Beach'),
    (1904, 'Plack Beach - Spin Pipe Piece 5', 'Spin Pipe Piece', 'Plack Beach'),
    (1905, 'Plack Beach - Spin Pipe Piece 6', 'Spin Pipe Piece', 'Plack Beach'),
    (1906, 'Plack Beach - Spin Pipe Piece 7', 'Spin Pipe Piece', 'Plack Beach'),
    (1907, 'Plack Beach - Spin Pipe Piece 8', 'Spin Pipe Piece', 'Plack Beach'),
    (1908, 'Plack Beach - Spin Pipe Piece 9', 'Spin Pipe Piece', 'Plack Beach'),
    (1909, 'Plack Beach - Spin Pipe Piece 10', 'Spin Pipe Piece', 'Plack Beach'),
    (1920, 'Flab Zone - Jump Helmet Pieces 2-5', 'Jump Helmet Piece', 'Flab Zone'),
    (1921, 'Flab Zone - Jump Helmet Piece 1', 'Jump Helmet Piece', 'Flab Zone'),
    (1922, 'Flab Zone - Jump Helmet Pieces 6-9', 'Jump Helmet Piece', 'Flab Zone'),
    (1923, 'Flab Zone - Jump Helmet Piece 10', 'Jump Helmet Piece', 'Flab Zone'),
    (1972, 'Energy Hold - Super Bouncer Piece 6', 'Super Bouncer Piece', 'Energy Hold'),
    (1973, 'Energy Hold - Super Bouncer Piece 1', 'Super Bouncer Piece', 'Energy Hold'),
    (1974, 'Energy Hold - Super Bouncer Piece 7', 'Super Bouncer Piece', 'Energy Hold'),
    (1975, 'Energy Hold - Super Bouncer Piece 8', 'Super Bouncer Piece', 'Energy Hold'),
    (1976, 'Energy Hold - Super Bouncer Piece 10', 'Super Bouncer Piece', 'Energy Hold'),
    (1977, 'Energy Hold - Super Bouncer Piece 9', 'Super Bouncer Piece', 'Energy Hold'),
    (1980, 'Energy Hold - Super Bouncer Pieces 2-5', 'Super Bouncer Piece', 'Energy Hold'),
    (1988, 'Toad Town - Mighty Meteor Piece 1', 'Mighty Meteor Piece', 'Toad Town'),
    (1989, 'Toad Town - Mighty Meteor Piece 2', 'Mighty Meteor Piece', 'Toad Town'),
    (1990, 'Toad Town - Mighty Meteor Piece 3', 'Mighty Meteor Piece', 'Toad Town'),
    (1991, 'Toad Town - Mighty Meteor Piece 4', 'Mighty Meteor Piece', 'Toad Town'),
    (1992, 'Toad Town - Mighty Meteor Piece 5', 'Mighty Meteor Piece', 'Toad Town'),
    (1993, 'Toad Town - Mighty Meteor Piece 6', 'Mighty Meteor Piece', 'Toad Town'),
    (1994, 'Toad Town - Mighty Meteor Piece 7', 'Mighty Meteor Piece', 'Toad Town'),
    (1995, 'Toad Town - Mighty Meteor Piece 8', 'Mighty Meteor Piece', 'Toad Town'),
    (1996, 'Toad Town - Mighty Meteor Piece 9', 'Mighty Meteor Piece', 'Toad Town'),
    (1997, 'Toad Town - Mighty Meteor Piece 10', 'Mighty Meteor Piece', 'Toad Town'),
    (2046, 'Dimble Wood - Snack Basket Piece 1', 'Snack Basket Piece', 'Dimble Wood'),
    (2047, 'Dimble Wood - Snack Basket Piece 2', 'Snack Basket Piece', 'Dimble Wood'),
    (2048, 'Dimble Wood - Snack Basket Piece 3', 'Snack Basket Piece', 'Dimble Wood'),
    (2049, 'Dimble Wood - Snack Basket Piece 4', 'Snack Basket Piece', 'Dimble Wood'),
    (2050, 'Dimble Wood - Snack Basket Piece 5', 'Snack Basket Piece', 'Dimble Wood'),
    (2051, 'Dimble Wood - Snack Basket Piece 6', 'Snack Basket Piece', 'Dimble Wood'),
    (2052, 'Dimble Wood - Snack Basket Piece 7', 'Snack Basket Piece', 'Dimble Wood'),
    (2053, 'Dimble Wood - Snack Basket Piece 8', 'Snack Basket Piece', 'Dimble Wood'),
    (2054, 'Dimble Wood - Snack Basket Piece 9', 'Snack Basket Piece', 'Dimble Wood'),
    (2055, 'Dimble Wood - Snack Basket Piece 10', 'Snack Basket Piece', 'Dimble Wood'),
    (2062, "Peach's Castle - Falling Star Piece 1", 'Falling Star Piece', "Peach's Castle"),
    (2063, "Peach's Castle - Falling Star Piece 2", 'Falling Star Piece', "Peach's Castle"),
    (2064, "Peach's Castle - Falling Star Piece 3", 'Falling Star Piece', "Peach's Castle"),
    (2065, "Peach's Castle - Falling Star Piece 4", 'Falling Star Piece', "Peach's Castle"),
    (2066, "Peach's Castle - Falling Star Piece 5", 'Falling Star Piece', "Peach's Castle"),
    (2067, "Peach's Castle - Falling Star Piece 6", 'Falling Star Piece', "Peach's Castle"),
    (2068, "Peach's Castle - Falling Star Piece 7", 'Falling Star Piece', "Peach's Castle"),
    (2069, "Peach's Castle - Falling Star Piece 8", 'Falling Star Piece', "Peach's Castle"),
    (2070, "Peach's Castle - Falling Star Piece 9", 'Falling Star Piece', "Peach's Castle"),
    (2071, "Peach's Castle - Falling Star Piece 10", 'Falling Star Piece', "Peach's Castle"),
    (2072, 'Bowser Castle - Magic Window Piece 1', 'Magic Window Piece', 'Bowser Castle'),
    (2073, 'Bowser Castle - Magic Window Piece 2', 'Magic Window Piece', 'Bowser Castle'),
    (2074, 'Bowser Castle - Magic Window Piece 3', 'Magic Window Piece', 'Bowser Castle'),
    (2075, 'Bowser Castle - Magic Window Piece 4', 'Magic Window Piece', 'Bowser Castle'),
    (2076, 'Bowser Castle - Magic Window Piece 5', 'Magic Window Piece', 'Bowser Castle'),
    (2077, 'Bowser Castle - Magic Window Piece 6', 'Magic Window Piece', 'Bowser Castle'),
    (2078, 'Bowser Castle - Magic Window Piece 7', 'Magic Window Piece', 'Bowser Castle'),
    (2079, 'Bowser Castle - Magic Window Piece 8', 'Magic Window Piece', 'Bowser Castle'),
    (2080, 'Bowser Castle - Magic Window Piece 9', 'Magic Window Piece', 'Bowser Castle'),
    (2081, 'Bowser Castle - Magic Window Piece 10', 'Magic Window Piece', 'Bowser Castle'),
]

# toutes les locations, tresors puis pieces d'attaque
LOCATIONS = TREASURES + ATTACK_PIECES

# zones portant au moins un tresor, dans l'ordre d'apparition
ZONES = [
    'Pump Works',
    'Plack Beach',
    "Peach's Castle",
    'Dimble Wood',
    'Flab Zone',
    'Bowser Path',
    'Bumpsy Plains',
    'Bowser Castle',
    'Blubble Lake',
    'Toad Town',
    'Tower of Yikk',
    'Tunnel',
    'Energy Hold',
    'Airway',
    'Cavi Cape',
    'Trash Pit',
]

# les regions dans l'ordre du parcours, avec la confiance
# qu'on a dans ce rang. Source : data/ordre_zones.csv
ZONE_ORDER = [
    (1, 'Trash Pit', 'guide'),
    (2, 'Cavi Cape', 'guide'),
    (3, 'Plack Beach', 'guide'),
    (4, 'Pump Works', 'guide'),
    (5, 'Dimble Wood', 'guide'),
    (6, 'Bumpsy Plains', 'guide'),
    (7, 'Bowser Path', 'guide'),
    (8, 'Flab Zone', 'guide'),
    (9, 'Tunnel', 'guide'),
    (10, 'Toad Town', 'guide'),
    (11, 'Blubble Lake', 'faible'),
    (12, 'Tower of Yikk', 'faible'),
    (13, 'Energy Hold', 'faible'),
    (14, 'Bowser Castle', 'faible'),
    (15, 'Airway', 'faible'),
    (16, "Peach's Castle", 'faible'),
]

# (nom d'item, variable 2xxx, zone ou le jeu l'octroie)
# Les seuls items de progression du monde.
CAPABILITIES = [
    ('Hammer', 0x2001, 'Trash Pit'),
    ('Spin Jump', 0x2002, 'Flab Zone'),
    ('Drill Bros', 0x2003, 'Energy Hold'),
    ('Sliding Haymaker', 0x2005, 'Dimble Wood'),
    ('Body Slam', 0x2006, 'Tower of Yikk'),
    ('Spike Ball', 0x2007, "Peach's Castle"),
    ('Vacuum Block', 0x200e, 'Plack Beach'),
    ('Blue Shell Blocks', 0x2025, 'Toad Town'),
    ('Air Vents', 0x202d, 'Toad Town'),
]

# nom d'item -> nombre d'exemplaires dans le jeu d'origine
VANILLA_ITEMS = {
    '1 Coins': 14,
    '1-Up Deluxe': 14,
    '1-Up Mushroom': 3,
    '10 Coins': 37,
    '100 Coins': 66,
    '25 Coins': 2,
    '250 Coins': 5,
    '300 Coins': 1,
    '5 Coins': 19,
    '50 Coins': 72,
    '500 Coins': 9,
    'Big Stomp Boots': 1,
    'Brawny Wear': 1,
    'Budget Charm': 1,
    'Burning Fangs': 1,
    'Bye-Bye Gloves': 2,
    'Cheap Ring': 1,
    'Coin Socks': 1,
    'D-Star Wear': 1,
    'DX POW Gloves': 2,
    'DX SP Socks': 1,
    'Delicious Gloves': 1,
    'Deluxe HP Socks': 1,
    'Drumstick Ring': 1,
    'EXP Socks': 1,
    'Economy Ring': 1,
    'Falling Star Piece': 10,
    'Fiery Drumstick': 2,
    'Fighter Wear': 1,
    'Fire Flower Piece': 10,
    'Flashy Fangs': 1,
    'Flower Gloves': 1,
    'Fury Fangs': 1,
    'Giant Shell': 1,
    'Green Shell Piece': 10,
    'Guardian Socks': 2,
    'Hard Ring': 1,
    'Heart Bean': 109,
    'Heart Wear': 1,
    'Hero Wear': 1,
    'Heroic Patch': 1,
    'Hot Drumstick': 9,
    'Ironclad Shell': 1,
    'Judge Shell': 1,
    'Jump Helmet Piece': 4,
    'KO Shell': 1,
    'King Wear': 1,
    'Luxury Patch': 1,
    'Magic Window Piece': 10,
    'Max Mushroom': 3,
    'Max Nut': 11,
    'Max Syrup Jar': 7,
    'Mighty Meteor Piece': 10,
    'Minion Band': 1,
    'Muscle Wear': 1,
    'Mushroom': 6,
    'Mushroom Gloves': 1,
    'Mushroom Stone': 1,
    'Nurse Socks': 1,
    'Nut': 1,
    'POW Boots': 1,
    'POW Mush Jam': 1,
    'Picnic Wear': 1,
    'Power Band': 1,
    'Power Band +': 1,
    'Power Bean': 36,
    'Rampage Shell': 1,
    'Red-hot Fangs': 1,
    'Refreshing Herb': 3,
    'Restore Ring': 1,
    'Retry Clock': 17,
    'Rock Shell': 1,
    'Rugged Socks': 1,
    'Safety Ring': 1,
    'Snack Basket Piece': 10,
    'Special Bean': 52,
    'Special Boots': 1,
    'Special Fangs': 1,
    'Special Fangs X': 1,
    'Spin Pipe Piece': 10,
    'Stamina Band': 1,
    'Star Candy': 21,
    'Star Wear': 1,
    'Super Bouncer Piece': 7,
    'Super Mushroom': 10,
    'Super Nut': 8,
    'Supersyrup Jar': 23,
    'Surprising Socks': 1,
    'Syrup Jar': 5,
    'TNT Drumstick': 10,
    'Thrift Charm': 1,
    'Ultra Mushroom': 7,
    'Ultra Nut': 3,
    'Ultrasyrup Jar': 5,
    'Wicked Shell': 1,
}

# nom d'item -> (categorie de livraison, valeur)
#   'coins'        montant a ajouter au u32 a 02056400   Verifie
#   'consumable'   index du compteur, 02056406 + index   Verifie
#   'gear'         compteur a 02056427 + id - 1          Verifie
#   'attack_piece' bit du champ 2xxx a 02056038          Verifie
ITEM_DELIVERY = {
    '1 Coins': ('coins', 1),
    '1-Up Deluxe': ('consumable', 17),
    '1-Up Mushroom': ('consumable', 16),
    '10 Coins': ('coins', 10),
    '100 Coins': ('coins', 100),
    '25 Coins': ('coins', 25),
    '250 Coins': ('coins', 250),
    '300 Coins': ('coins', 300),
    '5 Coins': ('coins', 5),
    '50 Coins': ('coins', 50),
    '500 Coins': ('coins', 500),
    'Air Vents': ('capability', 8237),
    'Big Stomp Boots': ('gear', 59),
    'Blue Shell Blocks': ('capability', 8229),
    'Body Slam': ('capability', 8198),
    'Brawny Wear': ('gear', 6),
    'Budget Charm': ('gear', 63),
    'Burning Fangs': ('gear', 109),
    'Bye-Bye Gloves': ('gear', 43),
    'Cheap Ring': ('gear', 115),
    'Coin Socks': ('gear', 23),
    'D-Star Wear': ('gear', 15),
    'DX POW Gloves': ('gear', 37),
    'DX SP Socks': ('gear', 21),
    'Delicious Gloves': ('gear', 41),
    'Deluxe HP Socks': ('gear', 19),
    'Drill Bros': ('capability', 8195),
    'Drumstick Ring': ('gear', 120),
    'EXP Socks': ('gear', 29),
    'Economy Ring': ('gear', 116),
    'Falling Star Piece': ('attack_piece', 8211),
    'Fiery Drumstick': ('consumable', 5),
    'Fighter Wear': ('gear', 4),
    'Fire Flower Piece': ('attack_piece', 8217),
    'Flashy Fangs': ('gear', 114),
    'Flower Gloves': ('gear', 42),
    'Fury Fangs': ('gear', 110),
    'Giant Shell': ('gear', 70),
    'Green Shell Piece': ('attack_piece', 8208),
    'Guardian Socks': ('gear', 35),
    'Hammer': ('capability', 8193),
    'Hard Ring': ('gear', 127),
    'Heart Bean': ('consumable', 20),
    'Heart Wear': ('gear', 5),
    'Hero Wear': ('gear', 9),
    'Heroic Patch': ('gear', 67),
    'Hot Drumstick': ('consumable', 4),
    'Ironclad Shell': ('gear', 90),
    'Judge Shell': ('gear', 84),
    'Jump Helmet Piece': ('attack_piece', 8214),
    'KO Shell': ('gear', 71),
    'King Wear': ('gear', 13),
    'Luxury Patch': ('gear', 66),
    'Magic Window Piece': ('attack_piece', 8219),
    'Max Mushroom': ('consumable', 3),
    'Max Nut': ('consumable', 10),
    'Max Syrup Jar': ('consumable', 14),
    'Mighty Meteor Piece': ('attack_piece', 8216),
    'Minion Band': ('gear', 95),
    'Muscle Wear': ('gear', 11),
    'Mushroom': ('consumable', 0),
    'Mushroom Gloves': ('gear', 38),
    'Mushroom Stone': ('gear', 75),
    'Nurse Socks': ('gear', 31),
    'Nut': ('consumable', 7),
    'POW Boots': ('gear', 48),
    'POW Mush Jam': ('gear', 76),
    'Picnic Wear': ('gear', 2),
    'Power Band': ('gear', 93),
    'Power Band +': ('gear', 94),
    'Power Bean': ('consumable', 22),
    'Rampage Shell': ('gear', 87),
    'Red-hot Fangs': ('gear', 108),
    'Refreshing Herb': ('consumable', 18),
    'Restore Ring': ('gear', 123),
    'Retry Clock': ('consumable', 23),
    'Rock Shell': ('gear', 85),
    'Rugged Socks': ('gear', 28),
    'Safety Ring': ('gear', 126),
    'Sliding Haymaker': ('capability', 8197),
    'Snack Basket Piece': ('attack_piece', 8218),
    'Special Bean': ('consumable', 21),
    'Special Boots': ('gear', 51),
    'Special Fangs': ('gear', 106),
    'Special Fangs X': ('gear', 107),
    'Spike Ball': ('capability', 8199),
    'Spin Jump': ('capability', 8194),
    'Spin Pipe Piece': ('attack_piece', 8209),
    'Stamina Band': ('gear', 99),
    'Star Candy': ('consumable', 15),
    'Star Wear': ('gear', 14),
    'Super Bouncer Piece': ('attack_piece', 8215),
    'Super Mushroom': ('consumable', 1),
    'Super Nut': ('consumable', 8),
    'Supersyrup Jar': ('consumable', 12),
    'Surprising Socks': ('gear', 34),
    'Syrup Jar': ('consumable', 11),
    'TNT Drumstick': ('consumable', 6),
    'Thrift Charm': ('gear', 62),
    'Ultra Mushroom': ('consumable', 2),
    'Ultra Nut': ('consumable', 9),
    'Ultrasyrup Jar': ('consumable', 13),
    'Vacuum Block': ('capability', 8206),
    'Wicked Shell': ('gear', 89),
}
